name: Add Rules to Cloudflare Gateway Daily
on:
  schedule:
    - cron: "10 20 * * *"
  push:
    paths:
      - lists.txt
      - whitelists.txt
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download latest build
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: "nhubaotruong/Cloudflare-Gateway-Pihole-Rs"
          file: "cloudflare_gateway_pihole"

      - name: Run
        run: |
          chmod +x cloudflare_gateway_pihole
          ./cloudflare_gateway_pihole
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
