name: Add Rules to Cloudflare Gateway Daily
on:
  schedule:
    - cron: "10 21 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: cloudflare_gateway_pihole:latest
      
      - name: Run
        run: |
          docker run --name cloudflare_gateway_pihole --env CF_API_TOKEN=$CF_API_TOKEN --env CF_IDENTIFIER=$CF_IDENTIFIER cloudflare_gateway_pihole:latest
        env: 
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      
      - name: Clean old cache
        uses: MyAlbum/purge-cache@v2
        with:
          max-age: 259200
