name: Add Rules to Cloudflare Gateway Daily
on:
  schedule:
    - cron: "10 22 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Download latest build
      #   uses: dsaltares/fetch-gh-release-asset@1.1.1
      #   with:
      #     repo: "nhubaotruong/Cloudflare-Gateway-Pihole-Rs"
      #     file: "cloudflare_gateway_pihole"
      
      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          make-default: true
      
      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release --locked

      - name: Run
        run: cargo run --release
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
