name: Rust Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup mold
        uses: rui314/setup-mold@v1
        with:
          make-default: true

      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Build
        run: cargo build --release --locked --target x86_64-unknown-linux-gnu

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: cloudflare_gateway_pihole
          path: target/release/cloudflare_gateway_pihole
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: cloudflare_gateway_pihole
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/cloudflare_gateway_pihole
          tag_name: ${{ github.ref }}
